### ISSUE TITLE
Can not read remote ZIP archives on latest chrome.

### ISSUE THREAD

**Issue by lixingmao** [lunu-bounir/zip-manager#3]
After installing the plug-in, when you click simple.zip on the test page https://webbrowsertools.com/test-download-with/, the file is downloaded directly, but it is not opened in the zip mananger. The latest Chrome has a new Is it restricted? Is there a solution? For example, turn on a flag and the like.

**Comment by lunu-bounir** [comment]
Use the right-click context menu -> "Open with ZIP Manager" item

**Comment by loyalty42** [comment]
what's the issued with the project/
